package com.schoolerc.fiftheditioncompanion.rules;

/**
 * Created by Chaz on 4/29/2017.
 */

public enum Property {
    StrengthScore,
    DexterityScore,
    ConstitutionScore,
    IntelligenceScore,
    WisdomScore,
    CharismaScore,
    StrengthBonus,
    DexterityBonus,
    ConstitutionBonus,
    IntelligenceBonus,
    WisdomBonus,
    CharismaBonus,
    StrengthSave,
    DexteritySave,
    ConstitutionSave,
    IntelligenceSave,
    WisdomSave,
    CharismaSave,
    StrengthSaveProficiency,
    DexteritySaveProficiency,
    ConstitutionSaveProficiency,
    IntelligenceSaveProficiency,
    WisdomSaveProficiency,
    CharismaSaveProficiency,
    AcrobaticsBonus,
    AnimalHandlingBonus,
    ArcanaBonus,
    AthleticsBonus,
    DeceptionBonus,
    HistoryBonus,
    InsightBonus,
    IntimidationBonus,
    InvestigationBonus,
    MedicineBonus,
    NatureBonus,
    PerceptionBonus,
    PerformanceBonus,
    PersuasionBonus,
    ReligionBonus,
    SleightOfHandBonus,
    StealthBonus,
    SurvivalBonus,
}
