package com.schoolerc.fiftheditioncompanion.components.parsing;

/**
 * Created by Chaz Schooler on 4/12/2017.
 */

public enum Token {
    EOF,
    CharacterBegin,
    CharacterEnd,
    NameBegin,
    NameEnd,
    AbilityScoresBegin,
    AbilityScoresEnd,
    StrengthBegin,
    StrengthEnd,
    DexterityBegin,
    DexterityEnd,
    ConstitutionBegin,
    ConstitutionEnd,
    IntelligenceBegin,
    IntelligenceEnd,
    WisdomBegin,
    WisdomEnd,
    CharismaBegin,
    CharismaEnd,
    RaceBegin, //Tokenized, partial implementation and parsing
    RaceEnd,
    ClassBegin,  //Tokenized, not implemented, not parsed
    ClassEnd,
    AbilityScoreModifierBegin,
    AbilityScoreModifierEnd,
    AbilityScoreTargetBegin,
    AbilityScoreTargetEnd,
    ValueBegin,
    ValueEnd,
    Text,
    Number,
    Strength,
    Dexterity,
    Constitution,
    Intelligence,
    Wisdom,
    Charisma,
    ChooseBegin,
    ChooseEnd,
    QuantityBegin,
    QuantityEnd,
    OptionsBegin,
    OptionsEnd,
    ClassProxyBegin, //Tokenized, not implemented, not parsed
    ClassProxyEnd,
    RaceProxyBegin, //Tokenized, not implemented, not parsed
    RaceProxyEnd,
    SubraceBegin, //Tokenized, not implemented, not parsed
    SubraceEnd,
    SubraceProxyBegin, //Tokenized, not implemented, not parsed
    SubraceProxyEnd,
    DescriptionBegin,
    DescriptionEnd,
    TraitBegin,
    TraitEnd,
    ComponentListBegin,
    ComponentListEnd,   //Everything below here has been tokenized, nothing else
    LanguageBegin,
    LanguageEnd,
    ProficiencyBegin,
    ProficiencyEnd,
    WeaponBegin,
    WeaponEnd,
    ArmorBegin,
    ArmorEnd,
    SavingThrowBegin,
    SavingThrowEnd,
    SkillCheckBegin,
    SkillCheckEnd,
    SkillBegin,
    SkillEnd,
    ToolBegin,
    ToolEnd,
    Athletics,
    Acrobatics,
    Arcana,
    AnimalHandling,
    History,
    Deception,
    Insight,
    Perception,
    SleightOfHand,
    Stealth,
    Nature,
    Medicine,
    Religion,
    Investigation,
    Survival,
    Persuasion,
    Performance,
    Intimidation,
}
